# 7x7 Xiangqi variant for Fairy-Stockfish.
# Load with: fairy-stockfish.exe load variants.ini

[mini7xiangqi]
variantTemplate = fairy
maxRank = 7
maxFile = 7

rook = r
cannon = c
horse = h
king = k:W
customPiece1 = p:fsW

pieceValueMg = p:300 h:720 c:760 r:1276
pieceValueEg = p:360 h:760 c:800 r:1380

startFen = rchkhcr/p1ppp1p/7/7/7/P1PPP1P/RCHKHCR w - - 0 1

mobilityRegionWhiteKing = c1 d1 e1 c2 d2 e2 c3 d3 e3
mobilityRegionBlackKing = c5 d5 e5 c6 d6 e6 c7 d7 e7

flyingGeneral = true
castling = false
doubleStep = false
pawnTypes = -
promotionPawnTypes = -
enPassantTypes = -
stalemateValue = loss
nMoveRule = 0
nFoldRule = 3
nFoldValue = draw

